name: github_repo_viewer
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  oauth2: ^2.0.1
  flutter_secure_storage: ^7.0.1
  dartz: ^0.10.1
  dio: ^4.0.6
  flutter_hooks: ^0.18.5+1
  hooks_riverpod: ^2.1.3
  freezed_annotation: ^2.2.0
  webview_flutter: ^4.0.1
  webview_flutter_web: ^0.2.1
  auto_route: ^5.0.4
  material_design_icons_flutter: ^6.0.7096
  json_annotation: ^4.7.0
  sembast: ^3.3.1+1
  path_provider: ^2.0.11
  path: ^1.8.3
  cached_network_image: ^3.2.3
  shimmer: ^2.0.0
  flash: ^2.0.5
  material_floating_search_bar: ^0.3.7
  url_launcher: ^6.1.7

dependency_overrides:
  path: 1.8.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.3
  freezed: ^2.3.2
  auto_route_generator: ^5.0.3
  json_serializable: ^6.5.4
  lint: ^2.0.1

flutter:
  uses-material-design: true
